### ISSUE TITLE
Filetype .ino instead of .pde

### ISSUE THREAD

**Issue by barry-ha** [markfickett/arduinomorse#10]
Hi, I was looking for a simple Morse code example and found this one. Thanks for providing concurrent execution - this will be helpful in sending canned Morse messages from my device that needs to continue sampling a GPS.

I had a little trouble getting started. The example files use PDE file extension, which the Arduino workbench can open, but Windows doesn't have a file association for it. I believe Arduino switched from PDE to avoid conflicts with some other existing programs and uses .INO instead. 

If you don't mind, can you rename your examples with .ino? This would be helpful to the next person who comes on board.

**Comment by markfickett** [comment]
Glad you're finding the library useful! Changed.
