### ISSUE TITLE
Control the delay between repeating message?

### ISSUE THREAD

**Issue by xseignard** [markfickett/arduinomorse#5]
Hello,

First, thanks for your lib, very helpful and well designed!

I'm doing a repeating morse sequence in a non-blocking way, so I play with `continueSending` and `startSending`, everything is great.

Now I'd like to add some time before starting again the `sending`, in a non-blocking way too.

For now I rely on some `millis()` calculation on my side, but I was wondering if there is something already implemented in your lib for my case?

FIY, here is my code https://github.com/xseignard/morse/blob/master/src/main.ino#L29-L35

Regards,

Xavier

**Comment by markfickett** [comment]
Would it work to just add some spaces at the end of your message? For
example "hello  ".

Glad you're enjoying the library!

**Comment by xseignard** [comment]
Thanks for your quick answer!

I think I prefer my solution, but at least the next person facing the same situation as mine would have 2 solutions!

Regards,

Xavier
